### 获取令牌
POST {{baseUrl}}/user/auth
Content-Type: application/json

### 查询某个用户详情
GET {{baseUrl}}/user/1

### 更改用户状态
PUT {{baseUrl}}/user
Content-Type: application/json

{"nickname":"天天开心","status":1,"phone": "15105191183","id": 3}

###
POST {{baseUrl}}/user
Content-Type: application/json

{"nickname":"岁岁平安","password": "123456","phone": "15106191181","status":1}
###
